version: "3.8"

services:
  mysql:
    container_name: mysql-bsn
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: whatsapp_clone
      MYSQL_USER: root      # Changed from root
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"              # Added quotes for clarity
    networks:
      - whatsapp-clone
    restart: unless-stopped
  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:26.1.2
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - whatsapp-clone
    command:
      - "start-dev"
    restart: unless-stopped

networks:
  whatsapp-clone:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  keycloak:
    driver: local