spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whatsapp_clone?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/whatsapp-clone
  servlet:
    multipart:
      max-file-size: 50MB
  application:
    file:
      uploads:
        media-output-path: ./uploads

server:
  port:
    4200